# Generated by Django 5.0 on 2024-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('clname', models.CharField(max_length=10)),
                ('cadd', models.TextField(max_length=100)),
                ('phone', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CUSTOMER',
        ),
    ]
